#!/usr/bin/env python3
"""Figure 1 — study flow, generated from NUMBERS.tsv so it cannot go stale.

Every figure in this manuscript must be regenerable from the frozen basis. This
script reads NUMBERS.tsv (itself regenerated by generate_numbers.py) and emits a
CONSORT-style flow SVG. It FAILS LOUDLY on a missing key rather than emitting a
figure with a blank in it -- a silently missing number in a figure is exactly the
failure mode this project keeps hitting.

  python3 generate_numbers.py && python3 make_figure1_bp.py
  python3 make_figure1_bp.py --dark      # screen/slide variant

Output: FIGURE1_STUDY_FLOW.svg (and FIGURE1_STUDY_FLOW_dark.svg under --dark)

Colours are written as LITERAL HEX, not CSS custom properties. `var(--x)` is not
resolved by librsvg, by older Inkscape, or by most journal and LaTeX
rasterisation paths -- the first version of this script used custom properties
and rendered as a solid black rectangle under `rsvg-convert`. A manuscript figure
has to survive toolchains that predate CSS variables.
"""
import csv
import os
import sys

B = os.path.dirname(os.path.abspath(__file__))
NUMBERS = f"{B}/NUMBERS.tsv"

DARK = "--dark" in sys.argv
OUT = f"{B}/FIGURE1_STUDY_FLOW{'_dark' if DARK else ''}.svg"

LIGHT_T = dict(ink="#12120f", ink2="#4e4d49", muted="#84837c", rule="#d3d2cb",
               surface="#ffffff", soft="#faf9f7",
               accent="#2a78d6", accent_soft="#eaf2fc")
DARK_T = dict(ink="#f4f3ee", ink2="#c3c2b7", muted="#95948c", rule="#3a3a37",
              surface="#1a1a19", soft="#212120",
              accent="#3987e5", accent_soft="#16283d")
T = DARK_T if DARK else LIGHT_T

# --------------------------------------------------------------- the numbers --
if not os.path.isfile(NUMBERS):
    sys.exit(f"FATAL: {NUMBERS} not found. Run generate_numbers.py first.")

N = {r["key"]: r["value"] for r in csv.DictReader(open(NUMBERS), delimiter="\t")}


def num(key):
    """Fetch a key or die. Never let a figure ship with a hole in it."""
    if key not in N:
        sys.exit(f"FATAL: NUMBERS.tsv has no key {key!r}. "
                 "Re-run generate_numbers.py; do not hand-edit this figure.")
    return N[key]


def comma(key):
    v = num(key)
    try:
        return f"{int(v):,}"
    except ValueError:
        return v


# Figures that are structural to the partition derivation and live in
# METHODS_DRAFT 2.12.5 rather than NUMBERS.tsv. Kept here as named constants so
# a reader can see they are NOT sourced from the frozen table.
PARTITION_STEPS = [
    ("after the n ≥ 7 rule", "86 units / 2,352 genomes"),
    ("− strain_1_L1_10, left below the floor", "85 / 2,345"),
    ("− 4 further duplicate BioSamples", "85 / 2,341"),
    ("− SRR2896257 (disclosed, §2.12.5)", "85 / 2,340"),
]
REPLICON_UNITS = 170
UNIT_MIN, UNIT_MED, UNIT_MAX = 7, 18, 159
POPPUNK_STRAINS = 28
GATE1_LO, GATE1_HI = "700", "4,700"

# ------------------------------------------------------------------- layout --
W, H = 920, 1246
COL_X, COL_W = 124, 432         # main spine column
EX_X, EX_W = 592, 300           # exclusion column
SPINE = COL_X + COL_W / 2

E = {  # xml escaping for the few strings that need it
    "&": "&amp;", "<": "&lt;", ">": "&gt;",
}


def esc(s):
    for k, v in E.items():
        s = s.replace(k, v)
    return s


parts = []


def box(x, y, w, h, kind="plain"):
    cls = {"plain": "bx", "key": "bx key", "ex": "bx ex"}[kind]
    parts.append(f'<rect class="{cls}" x="{x}" y="{y}" '
                 f'width="{w}" height="{h}" rx="5"/>')


def text(x, y, s, cls="h", anchor="start"):
    parts.append(f'<text class="{cls}" x="{x}" y="{y}" '
                 f'text-anchor="{anchor}">{esc(s)}</text>')


def arrow(y0, y1):
    parts.append(f'<line class="flow" x1="{SPINE}" y1="{y0}" '
                 f'x2="{SPINE}" y2="{y1}" marker-end="url(#a)"/>')


def elbow(y, y_to):
    """Spine -> exclusion box, CONSORT style."""
    parts.append(f'<path class="flow ex" d="M {SPINE} {y} V {y_to} '
                 f'H {EX_X}" marker-end="url(#ax)"/>')


def stage(y, label):
    text(30, y, label, cls="stage")
    parts.append(f'<line class="rail" x1="30" y1="{y + 8}" '
                 f'x2="104" y2="{y + 8}"/>')


# ---------------------------------------------------------------- the boxes --
# A. Source
stage(96, "SOURCE")
box(COL_X, 78, COL_W, 66)
text(COL_X + 18, 104, "ENA " + "B. pseudomallei" + " BioSamples", cls="h")
text(COL_X + 18, 126,
     f"{comma('ena.biosamples_union')} records (read_run ∪ assembly) — "
     f"{comma('ena.biosamples_with_country')} carry a country label,",
     cls="s")
text(COL_X + 18, 140, f"across {num('ena.countries')} countries", cls="s")
arrow(144, 186)

# B. Panel
stage(214, "PANEL")
box(COL_X, 188, COL_W, 62)
text(COL_X + 18, 213, "Assemblies considered", cls="h")
text(COL_X + COL_W - 18, 213, comma("panel.v4c"), cls="n", anchor="end")
text(COL_X + 18, 236,
     "2,802 from the curated collection + 174 newly added isolates", cls="s")
elbow(266, 266)
box(EX_X, 240, EX_W, 52, kind="ex")
text(EX_X + 14, 262,
     f"− {num('panel.removed_duplicate')} duplicate BioSamples", cls="exh")
text(EX_X + 14, 279,
     "deduplicated on BioSample, not run accession", cls="exs")
arrow(250, 296)

box(COL_X, 298, COL_W, 92, kind="key")
text(COL_X + 18, 324, "Genome panel", cls="hk")
text(COL_X + COL_W - 18, 324, comma("panel.corrected_v4d"), cls="nk", anchor="end")
text(COL_X + 18, 347,
     f"{num('panel.countries')} countries · "
     f"{num('panel.in_house')} in-house, "
     f"{comma('panel.public_derived')} public-derived", cls="s")
text(COL_X + 18, 364,
     f"{num('panel.coverage_of_ena')} of the country-labelled ENA BioSamples · "
     f"{comma('panel.region_labelled')} region-labelled", cls="s")
text(COL_X + 18, 381,
     f"Thailand {num('panel.top_country.Thailand').replace('1753', '1,753')} — top three "
     f"{num('panel.top3_share')} of the panel", cls="sw")
arrow(390, 436)

# C. Partition
stage(464, "PARTITION")
box(COL_X, 438, COL_W, 62)
text(COL_X + 18, 463, "PopPUNK strains → fastbaps L1 units", cls="h")
text(COL_X + 18, 486, "units of n ≥ 7 retained", cls="s")
elbow(516, 516)
box(EX_X, 438, EX_W, 116, kind="ex")
text(EX_X + 14, 459, "Correction of the partition", cls="exh")
for i, (lab, val) in enumerate(PARTITION_STEPS):
    yy = 478 + i * 18
    text(EX_X + 14, yy, lab, cls="exs")
    text(EX_X + EX_W - 14, yy, val, cls="exv", anchor="end")
arrow(500, 570)

box(COL_X, 572, COL_W, 92, kind="key")
text(COL_X + 18, 598, "Reported partition", cls="hk")
text(COL_X + COL_W - 18, 598,
     f"{num('units.analysed')} units", cls="nk", anchor="end")
text(COL_X + 18, 621,
     f"{comma('genomes.analysed')} genomes in {REPLICON_UNITS} replicon-units",
     cls="s")
text(COL_X + 18, 638,
     f"unit size min {UNIT_MIN}, median {UNIT_MED}, max {UNIT_MAX} · "
     f"from {POPPUNK_STRAINS} PopPUNK strains", cls="s")
text(COL_X + 18, 655,
     "22-core workstation run; the 88-unit A100 run is the cross-hardware control",
     cls="sw")
arrow(664, 710)

# D. Recombination
stage(738, "RECOMBINATION")
box(COL_X, 712, COL_W, 52)
text(COL_X + 18, 737, "Gubbins recombination inference", cls="h")
text(COL_X + 18, 756, f"run on all {num('units.analysed')} units", cls="s")
elbow(780, 780)
box(EX_X, 712, EX_W, 88, kind="ex")
text(EX_X + 14, 733, "Outside the Gate 1 window", cls="exh")
text(EX_X + EX_W - 14, 733, "38 units", cls="exv", anchor="end")
text(EX_X + 14, 752, "12 below floor, 26 above ceiling; median r/m "
     + num("rm.median_outside_gate1"), cls="exs")
text(EX_X + 14, 770, "r/m withheld — a low value here is a detection",
     cls="exs")
text(EX_X + 14, 786, "failure, not biology. Retained for phylogeny.", cls="exs")
arrow(764, 810)

box(COL_X, 812, COL_W, 74, kind="key")
text(COL_X + 18, 838, "Gate 1 in-window", cls="hk")
text(COL_X + COL_W - 18, 838, f"{num('rm.gate1_units')} units", cls="nk", anchor="end")
text(COL_X + 18, 861,
     f"median r/m = {num('rm.median_gate1')} — the reported recombination result",
     cls="s")
text(COL_X + 18, 878,
     f"window [{GATE1_LO}, {GATE1_HI}] mean pairwise core SNPs, alignment-derived",
     cls="sw")
arrow(886, 932)

# E. Attribution
stage(960, "ATTRIBUTION")
box(COL_X, 934, COL_W, 62)
text(COL_X + 18, 959, "cgMLST typing", cls="h")
text(COL_X + 18, 982,
     f"Lichtenegger v1.1, 4,221 loci · {comma('cgmlst.genomes')} genomes, "
     f"median call rate {num('cgmlst.call_rate_median')}", cls="s")
arrow(996, 1042)

box(COL_X, 1044, COL_W, 58)
text(COL_X + 18, 1069, "Validation set", cls="h")
text(COL_X + COL_W - 18, 1069, f"{num('validation.scorable')} scorable",
     cls="n", anchor="end")
text(COL_X + 18, 1090,
     f"{num('validation.total')} registered · 45 individuals · "
     f"{num('validation.source_countries')} source countries", cls="s")
elbow(1112, 1112)
box(EX_X, 1092, EX_W, 52, kind="ex")
text(EX_X + 14, 1113, "− 2 non-country exposures", cls="exh")
text(EX_X + 14, 1130, "'Africa', 'Panama and Peru' — unattributable",
     cls="exs")
# Fork to the two outcomes rather than pointing into the gap between them.
ow = (COL_W - 20) / 2
_l, _r = COL_X + ow / 2, COL_X + ow + 20 + ow / 2
parts.append(f'<path class="flow" d="M {SPINE} 1102 V 1126 M {_l} 1126 H {_r}"/>')
parts.append(f'<line class="flow" x1="{_l}" y1="1126" x2="{_l}" y2="1136" '
             f'marker-end="url(#a)"/>')
parts.append(f'<line class="flow" x1="{_r}" y1="1126" x2="{_r}" y2="1136" '
             f'marker-end="url(#a)"/>')

# Two outcomes, side by side.
box(COL_X, 1138, ow, 84, kind="key")
text(COL_X + 16, 1162, "Region, modal k = 20", cls="hk2")
text(COL_X + 16, 1186, num("attribution.region.modal_k20"), cls="nk")
text(COL_X + 16, 1206,
     f"κ {num('ladder.region_7way.kappa')} · baseline 45.7%", cls="s")

box(COL_X + ow + 20, 1138, ow, 84)
text(COL_X + ow + 36, 1162, "Country, nearest neighbour", cls="h2")
text(COL_X + ow + 36, 1186, num("attribution.country.nearest_neighbour"),
     cls="n")
text(COL_X + ow + 36, 1206,
     f"κ {num('ladder.country.kappa')} — does not exceed chance",
     cls="sw")

# ---------------------------------------------------------------- assemble --
SVG = f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}"
     width="{W}" height="{H}" role="img"
     aria-label="Study flow from ENA BioSamples through the reported partition
     to the two attribution outcomes">
<title>Figure 1. Study flow</title>
<style>
  text {{ font-family:"Helvetica Neue",Helvetica,Arial,sans-serif;
          fill:{T['ink']}; }}
  .bx {{ fill:{T['surface']}; stroke:{T['rule']}; stroke-width:1.25; }}
  .bx.key {{ fill:{T['accent_soft']}; stroke:{T['accent']}; stroke-width:1.5; }}
  .bx.ex  {{ fill:{T['soft']}; stroke:{T['rule']}; stroke-dasharray:3 3; }}
  .h  {{ font-size:14.5px; font-weight:600; }}
  .h2 {{ font-size:13px; font-weight:600; }}
  .hk2 {{ font-size:13px; font-weight:700; }}
  .hk {{ font-size:14.5px; font-weight:700; }}
  .n  {{ font-size:16px; font-weight:700; }}
  .nk {{ font-size:16px; font-weight:700; fill:{T['accent']}; }}
  .s  {{ font-size:11.5px; fill:{T['ink2']}; }}
  .sw {{ font-size:11px; fill:{T['muted']}; font-style:italic; }}
  .exh {{ font-size:12px; font-weight:600; fill:{T['ink2']}; }}
  .exs {{ font-size:10.8px; fill:{T['muted']}; }}
  .exv {{ font-size:10.8px; fill:{T['ink2']}; font-weight:600; }}
  .stage {{ font-size:8.5px; font-weight:700; letter-spacing:.06em;
            fill:{T['muted']}; }}
  .rail {{ stroke:{T['rule']}; stroke-width:1; }}
  .flow {{ stroke:{T['ink2']}; stroke-width:1.4; fill:none; }}
  .flow.ex {{ stroke:{T['rule']}; stroke-dasharray:3 3; }}
  .cap {{ font-size:11.5px; fill:{T['ink2']}; }}
</style>
<defs>
  <marker id="a" viewBox="0 0 8 8" refX="7" refY="4" markerWidth="7"
          markerHeight="7" orient="auto-start-reverse">
    <path d="M0 0.5 L 7.5 4 L 0 7.5 z" fill="{T['ink2']}"/>
  </marker>
  <marker id="ax" viewBox="0 0 8 8" refX="7" refY="4" markerWidth="6"
          markerHeight="6" orient="auto-start-reverse">
    <path d="M0 0.5 L 7.5 4 L 0 7.5 z" fill="{T['rule']}"/>
  </marker>
</defs>
<g>
<rect x="0" y="0" width="{W}" height="{H}" fill="{T['surface']}"/>
<text class="hk" x="30" y="40" style="font-size:17px">Figure 1. Study flow</text>
<text class="cap" x="30" y="60">From public deposition to the two attribution outcomes. Boxes in blue are the frozen analysis basis.</text>
{chr(10).join(parts)}
</g>
</svg>
'''

with open(OUT, "w") as fh:
    fh.write(SVG)

print(f"wrote {OUT}")
print(f"  panel            {comma('panel.corrected_v4d')}")
print(f"  partition        {num('units.analysed')} units / "
      f"{comma('genomes.analysed')} genomes")
print(f"  Gate 1 in-window {num('rm.gate1_units')} units, "
      f"median r/m {num('rm.median_gate1')}")
print(f"  validation       {num('validation.scorable')} scorable")
